# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YapAiTek-Assessment' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YapAiTek-Assessment

	pod 'OAuthSwift', '~> 2.0.0'
        pod 'Alamofire', '~> 4.7'
        pod 'RxSwift'
        pod 'RxCocoa'

    	#SDWebImage
   	 pod 'Kingfisher', '~> 4.0'



  target 'YapAiTek-AssessmentTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YapAiTek-AssessmentUITests' do
    # Pods for testing
  end

end
